# Generated by Django 4.1.3 on 2022-12-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='Diverse', max_length=200, verbose_name='a_gender')),
                ('first_name', models.CharField(default='Your First Name', max_length=200, verbose_name='a_firstname')),
                ('last_name', models.CharField(default='Your Last Name', max_length=200, verbose_name='a_lastname')),
                ('height', models.IntegerField(default=180, verbose_name='a_height')),
                ('weight', models.IntegerField(default=80, verbose_name='a_weight')),
                ('birth_date', models.DateField(default=2020, verbose_name='a_birthdate')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Your Description', max_length=200, verbose_name='w_description')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.athletes')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause', models.IntegerField(verbose_name='wd_pause')),
                ('start', models.IntegerField(verbose_name='wd_start')),
                ('end', models.IntegerField(verbose_name='wd_end')),
                ('duration', models.IntegerField(verbose_name='wd_duration')),
                ('date', models.DateField(verbose_name='wd_date')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.workout')),
            ],
        ),
    ]
