# Generated by Django 4.1.3 on 2022-12-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='birth_date',
            field=models.DateField(default=2020, verbose_name='Your Birthdate'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='first_name',
            field=models.CharField(default='Your First Name', max_length=200, verbose_name='Your First Name'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='gender',
            field=models.CharField(default='Diverse', max_length=200, verbose_name='Your Gender'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='height',
            field=models.IntegerField(default=180, verbose_name='Your Height'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='last_name',
            field=models.CharField(default='Your Last Name', max_length=200, verbose_name='Your Last Name'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='weight',
            field=models.IntegerField(default=80, verbose_name='Your Weight'),
        ),
    ]
