# Generated by Django 4.1.3 on 2022-12-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_athletes_birth_date_alter_athletes_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletes',
            name='birth_date',
        ),
    ]
