# Generated by Django 4.1.3 on 2022-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_remove_athletes_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(default='Your Description', max_length=200, verbose_name='Workout description'),
        ),
    ]
