# Generated by Django 4.1.3 on 2022-12-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_alter_workout_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_data',
            name='date',
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='duration',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='end',
            field=models.IntegerField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='pause',
            field=models.IntegerField(verbose_name='Pause'),
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='start',
            field=models.IntegerField(verbose_name='Start'),
        ),
    ]
