# Generated by Django 4.1.3 on 2022-12-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_remove_workout_data_date_alter_workout_data_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='athlete',
        ),
        migrations.AddField(
            model_name='workout_data',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.athletes'),
        ),
    ]
