# Generated by Django 4.1.3 on 2022-12-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_remove_workout_athlete_workout_data_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Your First Name'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='gender',
            field=models.CharField(max_length=200, verbose_name='Your Gender'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Your Last Name'),
        ),
    ]
