# Generated by Django 4.1.3 on 2022-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_alter_athletes_first_name_alter_athletes_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Diverse', 'diverse')], default='diverse', max_length=10),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='height',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='weight',
            field=models.IntegerField(default=80),
        ),
    ]
