# Generated by Django 4.1.3 on 2022-12-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_alter_athletes_first_name_alter_athletes_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
