# Generated by Django 4.1.3 on 2022-12-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_alter_athletes_height_alter_athletes_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
