# Generated by Django 4.1.3 on 2022-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0010_alter_workout_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_data',
            name='pause',
            field=models.TimeField(max_length=30),
        ),
    ]
