# Generated by Django 4.1.3 on 2022-12-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0011_alter_workout_data_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_data',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='end',
            field=models.TimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='pause',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='start',
            field=models.TimeField(max_length=30),
        ),
    ]
