# Generated by Django 4.1.3 on 2022-12-14 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0012_alter_workout_data_duration_alter_workout_data_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_data',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=30),
        ),
    ]
