# Generated by Django 4.1.3 on 2022-12-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0014_remove_workout_data_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_data',
            name='start',
            field=models.DateTimeField(max_length=30),
        ),
    ]
