# Generated by Django 4.1.3 on 2022-12-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0015_alter_workout_data_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_data',
            name='start',
            field=models.TimeField(max_length=30),
        ),
    ]
