# Generated by Django 4.1.3 on 2022-12-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0017_alter_workout_data_pause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_data',
            name='pause',
        ),
    ]
