# Generated by Django 4.1.3 on 2023-01-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0018_remove_workout_data_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='designation',
            field=models.CharField(default='Your Designation', max_length=50),
            preserve_default=False,
        ),
    ]
