# Generated by Django 4.1.3 on 2023-01-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0019_workout_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_data',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athletes'),
        ),
    ]
